// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/JhonasMutton/book-lender/pkg"
	"github.com/JhonasMutton/book-lender/pkg/api/config"
)

// Injectors from wire.go:

func SetupApplication() pkg.Application {
	handler := config.NewHandler()
	application := pkg.NewApplication(handler)
	return application
}
