START TRANSACTION;
CREATE TABLE
    USER(
    USER_ID    INT NOT NULL AUTO_INCREMENT,
    NAME       VARCHAR(100),
    EMAIL      VARCHAR(300) UNIQUE,
    CREATED_AT DATE,
    PRIMARY KEY (USER_ID)
);
COMMIT;

START TRANSACTION;
CREATE TABLE BOOK
(
    BOOK_ID    INT NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(100),
    PAGES      INT,
    CREATED_AT DATE,
    PRIMARY KEY (BOOK_ID)
);
COMMIT;

START TRANSACTION;
CREATE TABLE USER_BOOKS
(
    USER_BOOKS_ID INT NOT NULL AUTO_INCREMENT,
    FK_USER_ID    INT NOT NULL,
    FK_BOOK_ID    INT NOT NULL,
    PRIMARY KEY (USER_BOOKS_ID),
    FOREIGN KEY (FK_USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (FK_BOOK_ID) REFERENCES BOOK (BOOK_ID)
);
COMMIT;

START TRANSACTION;
CREATE TABLE LOAN_BOOKS
(
    LOAN_BOOKS_ID   INT NOT NULL AUTO_INCREMENT,
    FK_BOOK_ID      INT NOT NULL,
    FK_FROM_USER_ID INT NOT NULL,
    FK_TO_USER_ID   INT NOT NULL,
    LENT_AT         DATE,
    RETURNED_AT     DATE,
    IS_ACTIVE       BOOLEAN,
    PRIMARY KEY (LOAN_BOOKS_ID),
    FOREIGN KEY (FK_BOOK_ID) REFERENCES BOOK (BOOK_ID),
    FOREIGN KEY (FK_FROM_USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (FK_TO_USER_ID) REFERENCES USER (USER_ID)
);
COMMIT;